#!/bin/bash

# Generate the appropriate configuration.
cat > /etc/sysconfig/vms <<EOF
VMS_USER=$(config-get vms-user)
VMS_GROUP=$(config-get vms-group)
VMS_SHELF_PATH=$(config-get vms-shelf_path)
VMS_SHARED_PATH=$(config-get vms-shared_path)
VMS_DISK_URL=$(config-get vms-disk_url)
VMS_MEMORY_URL=$(config-get vms-memory_url)
VMS_LOGS=$(config-get vms-logs)
VMS_SINGLE_LOG=$(config-get vms-single_log)
VMS_CACHE=$(config-get vms-cache)
VMS_STORE=$(config-get vms-store)
VMSD_OPTS=$(config-get vms-vmsd_opts)
VMS_DEBUG=$(config-get vms-debug)
VMS_GUEST_PARAMS=$(config-get vms-guest_params)
VMS_CEPH_CONF=$(config-get vms-ceph_conf)
VMS_CEPH_LOGIN=$(config-get vms-ceph_login)
VMS_QEMU_CPU_MODEL=$(config-get vms-qemu_cpu_model)
EOF

# Restart to pick up changes.
service cobalt-compute restart
