#!/bin/bash

rm -f /etc/sysconfig/vms
rm -f /etc/apt/sources.list.d/cobalt-compute.list

# Ensure the key is added.
apt-key add - <<EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mQENBFAQqgUBCADOMIkW4BliIOZyks8addo/SJjXRVjbAs2/O5pINHTRRo8DabCB
ISbKAjmxpkepQ/mN2o4cxK+3IGpSVQhrhLRyBRRMZv1MH4n+Yoq2AemO83ILQthi
39jHwKm107untAeLKTwt1DSY1HnFEQJl5bwG7HHqz3iD9HCwY5bX4eDrm4AxW0NG
rPdZpnLcuZfgMWEzRnhSkaTrCKiysQs5BVF3twbmzgO6hK26XjEOCNeOgHWGAbjZ
tky9zcjg2c1FG6g7pYyPyeLkSpF+CfhYe5pclrSvB708wVb+NczBD9MfInV9Er9/
UYr2kd4rYttc/tUFSCPjKoT9grO7dtIHbZVtABEBAAG0J0dyaWRjZW50cmljIElu
Yy4gPGluZm9AZ3JpZGNlbnRyaWMuY29tPokBOAQTAQIAIgUCUBCqBQIbAwYLCQgH
AwIGFQgCCQoLBBYCAwECHgECF4AACgkQ9sSiVmboP0x1eAgAkpUEzJ5ZxjZPxbPH
de5ryZpUvb/3VKsXiV6mRPHM78Psdjc68dnm3n1V57g5zc57n2mD/li80Y+bqzgk
eWjMg6JRr1bBIgz2kKVtXQhmDWsk9tu3KW3AieVArsZWjGo8Oab4jNZO0gq2QOcR
Bt/uTYW2wU9xO0S/AyRtwBUqjDP7Q9LKp2i5UrBCtQfXQ1WFvUgQzhcYwFkoO/oH
bi4S4hcMsGBQjsrtQkorwj8Fp3QuUErvjnjT6+6RqO+W2SjYb7eFSBBHRD6Wnas4
TDETaIfuEOonLXzRjaQ2QTprVIZDQkY9Qnp/BZXfWheXeIkq6jsWyV87Wmwm+V8e
zGdl0Q==
=DHFj
-----END PGP PUBLIC KEY BLOCK-----
EOF

# Generate our package lists.
cat > /etc/apt/sources.list.d/cobalt-compute.list <<EOF
deb $(config-get base-uri)/$(config-get cobalt-key)/$(config-get os-version)/$(lsb_release -cs)/ gridcentric multiverse
deb $(config-get base-uri)/$(config-get vms-key)/vms/$(lsb_release -cs)/ gridcentric multiverse
EOF

# Generate the appropriate configuration.
cat > /etc/sysconfig/vms <<EOF
VMS_USER=$(config-get vms-user)
VMS_GROUP=$(config-get vms-group)
VMS_SHELF_PATH=$(config-get vms-shelf_path)
VMS_SHARED_PATH=$(config-get vms-shared_path)
VMS_DISK_URL=$(config-get vms-disk_url)
VMS_MEMORY_URL=$(config-get vms-memory_url)
VMS_LOGS=$(config-get vms-logs)
VMS_SINGLE_LOG=$(config-get vms-single_log)
VMS_CACHE=$(config-get vms-cache)
VMS_STORE=$(config-get vms-store)
VMSD_OPTS=$(config-get vms-vmsd_opts)
VMS_DEBUG=$(config-get vms-debug)
VMS_GUEST_PARAMS=$(config-get vms-guest_params)
VMS_CEPH_CONF=$(config-get vms-ceph_conf)
VMS_CEPH_LOGIN=$(config-get vms-ceph_login)
VMS_QEMU_CPU_MODEL=$(config-get vms-qemu_cpu_model)
EOF

# Restart to pick up changes.
service cobalt-compute restart
